// Code generated by entc, DO NOT EDIT.

package friendapply

const (
	// Label holds the string label denoting the friendapply type in the database.
	Label = "friend_apply"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFromID holds the string denoting the from_id field in the database.
	FieldFromID = "from_id"
	// FieldToID holds the string denoting the to_id field in the database.
	FieldToID = "to_id"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the friendapply in the database.
	Table = "friend_applies"
)

// Columns holds all SQL columns for friendapply fields.
var Columns = []string{
	FieldID,
	FieldFromID,
	FieldToID,
	FieldRemark,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
