version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    restart: always
    entrypoint: etcd
    command: >
      --data-dir=/data --name etcd1
      --advertise-client-urls http://etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster-token
      --initial-cluster "etcd1=http://etcd:2380"
      --initial-advertise-peer-urls "http://etcd:2380"
      --initial-cluster-state new
      --auto-compaction-retention=1
      --quota-backend-bytes=102400000
    volumes:
      - ./etcd-data:/data
    ports:
      - "2379:2379"
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_PASSWORD=123456

  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes --requirepass '123456'
    restart: always
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"

  go2o:
    image: dockerhub.com/voocel/social:latest
    depends_on:
      - "postgres"
      - "etcd"
      - "redis"
    restart: always
    ports:
      - "8800:8800"
      - "8100:8100"
    volumes:
      - ./social-data:/data
    environment:
      SOCIAL_ETCD_ADDR: etcd:2379
      SOCIAL_SERVER_HOST: