// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"social/ent/friendapply"
	"social/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendApplyQuery is the builder for querying FriendApply entities.
type FriendApplyQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FriendApply
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FriendApplyQuery builder.
func (faq *FriendApplyQuery) Where(ps ...predicate.FriendApply) *FriendApplyQuery {
	faq.predicates = append(faq.predicates, ps...)
	return faq
}

// Limit adds a limit step to the query.
func (faq *FriendApplyQuery) Limit(limit int) *FriendApplyQuery {
	faq.limit = &limit
	return faq
}

// Offset adds an offset step to the query.
func (faq *FriendApplyQuery) Offset(offset int) *FriendApplyQuery {
	faq.offset = &offset
	return faq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (faq *FriendApplyQuery) Unique(unique bool) *FriendApplyQuery {
	faq.unique = &unique
	return faq
}

// Order adds an order step to the query.
func (faq *FriendApplyQuery) Order(o ...OrderFunc) *FriendApplyQuery {
	faq.order = append(faq.order, o...)
	return faq
}

// First returns the first FriendApply entity from the query.
// Returns a *NotFoundError when no FriendApply was found.
func (faq *FriendApplyQuery) First(ctx context.Context) (*FriendApply, error) {
	nodes, err := faq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{friendapply.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (faq *FriendApplyQuery) FirstX(ctx context.Context) *FriendApply {
	node, err := faq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FriendApply ID from the query.
// Returns a *NotFoundError when no FriendApply ID was found.
func (faq *FriendApplyQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = faq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{friendapply.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (faq *FriendApplyQuery) FirstIDX(ctx context.Context) int64 {
	id, err := faq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FriendApply entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FriendApply entity is found.
// Returns a *NotFoundError when no FriendApply entities are found.
func (faq *FriendApplyQuery) Only(ctx context.Context) (*FriendApply, error) {
	nodes, err := faq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{friendapply.Label}
	default:
		return nil, &NotSingularError{friendapply.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (faq *FriendApplyQuery) OnlyX(ctx context.Context) *FriendApply {
	node, err := faq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FriendApply ID in the query.
// Returns a *NotSingularError when more than one FriendApply ID is found.
// Returns a *NotFoundError when no entities are found.
func (faq *FriendApplyQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = faq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = &NotSingularError{friendapply.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (faq *FriendApplyQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := faq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FriendApplies.
func (faq *FriendApplyQuery) All(ctx context.Context) ([]*FriendApply, error) {
	if err := faq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return faq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (faq *FriendApplyQuery) AllX(ctx context.Context) []*FriendApply {
	nodes, err := faq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FriendApply IDs.
func (faq *FriendApplyQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := faq.Select(friendapply.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (faq *FriendApplyQuery) IDsX(ctx context.Context) []int64 {
	ids, err := faq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (faq *FriendApplyQuery) Count(ctx context.Context) (int, error) {
	if err := faq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return faq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (faq *FriendApplyQuery) CountX(ctx context.Context) int {
	count, err := faq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (faq *FriendApplyQuery) Exist(ctx context.Context) (bool, error) {
	if err := faq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return faq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (faq *FriendApplyQuery) ExistX(ctx context.Context) bool {
	exist, err := faq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FriendApplyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (faq *FriendApplyQuery) Clone() *FriendApplyQuery {
	if faq == nil {
		return nil
	}
	return &FriendApplyQuery{
		config:     faq.config,
		limit:      faq.limit,
		offset:     faq.offset,
		order:      append([]OrderFunc{}, faq.order...),
		predicates: append([]predicate.FriendApply{}, faq.predicates...),
		// clone intermediate query.
		sql:    faq.sql.Clone(),
		path:   faq.path,
		unique: faq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FromID int64 `json:"from_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FriendApply.Query().
//		GroupBy(friendapply.FieldFromID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (faq *FriendApplyQuery) GroupBy(field string, fields ...string) *FriendApplyGroupBy {
	group := &FriendApplyGroupBy{config: faq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := faq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return faq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FromID int64 `json:"from_id,omitempty"`
//	}
//
//	client.FriendApply.Query().
//		Select(friendapply.FieldFromID).
//		Scan(ctx, &v)
func (faq *FriendApplyQuery) Select(fields ...string) *FriendApplySelect {
	faq.fields = append(faq.fields, fields...)
	return &FriendApplySelect{FriendApplyQuery: faq}
}

func (faq *FriendApplyQuery) prepareQuery(ctx context.Context) error {
	for _, f := range faq.fields {
		if !friendapply.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if faq.path != nil {
		prev, err := faq.path(ctx)
		if err != nil {
			return err
		}
		faq.sql = prev
	}
	return nil
}

func (faq *FriendApplyQuery) sqlAll(ctx context.Context) ([]*FriendApply, error) {
	var (
		nodes = []*FriendApply{}
		_spec = faq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &FriendApply{config: faq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, faq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (faq *FriendApplyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := faq.querySpec()
	_spec.Node.Columns = faq.fields
	if len(faq.fields) > 0 {
		_spec.Unique = faq.unique != nil && *faq.unique
	}
	return sqlgraph.CountNodes(ctx, faq.driver, _spec)
}

func (faq *FriendApplyQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := faq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (faq *FriendApplyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   friendapply.Table,
			Columns: friendapply.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: friendapply.FieldID,
			},
		},
		From:   faq.sql,
		Unique: true,
	}
	if unique := faq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := faq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendapply.FieldID)
		for i := range fields {
			if fields[i] != friendapply.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := faq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := faq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := faq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := faq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (faq *FriendApplyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(faq.driver.Dialect())
	t1 := builder.Table(friendapply.Table)
	columns := faq.fields
	if len(columns) == 0 {
		columns = friendapply.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if faq.sql != nil {
		selector = faq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if faq.unique != nil && *faq.unique {
		selector.Distinct()
	}
	for _, p := range faq.predicates {
		p(selector)
	}
	for _, p := range faq.order {
		p(selector)
	}
	if offset := faq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := faq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FriendApplyGroupBy is the group-by builder for FriendApply entities.
type FriendApplyGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fagb *FriendApplyGroupBy) Aggregate(fns ...AggregateFunc) *FriendApplyGroupBy {
	fagb.fns = append(fagb.fns, fns...)
	return fagb
}

// Scan applies the group-by query and scans the result into the given value.
func (fagb *FriendApplyGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fagb.path(ctx)
	if err != nil {
		return err
	}
	fagb.sql = query
	return fagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := fagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(fagb.fields) > 1 {
		return nil, errors.New("ent: FriendApplyGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := fagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) StringsX(ctx context.Context) []string {
	v, err := fagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplyGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) StringX(ctx context.Context) string {
	v, err := fagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(fagb.fields) > 1 {
		return nil, errors.New("ent: FriendApplyGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := fagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) IntsX(ctx context.Context) []int {
	v, err := fagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplyGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) IntX(ctx context.Context) int {
	v, err := fagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(fagb.fields) > 1 {
		return nil, errors.New("ent: FriendApplyGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := fagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := fagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplyGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) Float64X(ctx context.Context) float64 {
	v, err := fagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(fagb.fields) > 1 {
		return nil, errors.New("ent: FriendApplyGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := fagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := fagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fagb *FriendApplyGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplyGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fagb *FriendApplyGroupBy) BoolX(ctx context.Context) bool {
	v, err := fagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fagb *FriendApplyGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fagb.fields {
		if !friendapply.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fagb *FriendApplyGroupBy) sqlQuery() *sql.Selector {
	selector := fagb.sql.Select()
	aggregation := make([]string, 0, len(fagb.fns))
	for _, fn := range fagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fagb.fields)+len(fagb.fns))
		for _, f := range fagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fagb.fields...)...)
}

// FriendApplySelect is the builder for selecting fields of FriendApply entities.
type FriendApplySelect struct {
	*FriendApplyQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fas *FriendApplySelect) Scan(ctx context.Context, v interface{}) error {
	if err := fas.prepareQuery(ctx); err != nil {
		return err
	}
	fas.sql = fas.FriendApplyQuery.sqlQuery(ctx)
	return fas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fas *FriendApplySelect) ScanX(ctx context.Context, v interface{}) {
	if err := fas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Strings(ctx context.Context) ([]string, error) {
	if len(fas.fields) > 1 {
		return nil, errors.New("ent: FriendApplySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := fas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fas *FriendApplySelect) StringsX(ctx context.Context) []string {
	v, err := fas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fas *FriendApplySelect) StringX(ctx context.Context) string {
	v, err := fas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Ints(ctx context.Context) ([]int, error) {
	if len(fas.fields) > 1 {
		return nil, errors.New("ent: FriendApplySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := fas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fas *FriendApplySelect) IntsX(ctx context.Context) []int {
	v, err := fas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fas *FriendApplySelect) IntX(ctx context.Context) int {
	v, err := fas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(fas.fields) > 1 {
		return nil, errors.New("ent: FriendApplySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := fas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fas *FriendApplySelect) Float64sX(ctx context.Context) []float64 {
	v, err := fas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fas *FriendApplySelect) Float64X(ctx context.Context) float64 {
	v, err := fas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(fas.fields) > 1 {
		return nil, errors.New("ent: FriendApplySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := fas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fas *FriendApplySelect) BoolsX(ctx context.Context) []bool {
	v, err := fas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (fas *FriendApplySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{friendapply.Label}
	default:
		err = fmt.Errorf("ent: FriendApplySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fas *FriendApplySelect) BoolX(ctx context.Context) bool {
	v, err := fas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fas *FriendApplySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := fas.sql.Query()
	if err := fas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
