// Code generated by entc, DO NOT EDIT.

package groupmember

const (
	// Label holds the string label denoting the groupmember type in the database.
	Label = "group_member"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldInviter holds the string denoting the inviter field in the database.
	FieldInviter = "inviter"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldApplyAt holds the string denoting the apply_at field in the database.
	FieldApplyAt = "apply_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the groupmember in the database.
	Table = "group_members"
)

// Columns holds all SQL columns for groupmember fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldGroupID,
	FieldInviter,
	FieldRemark,
	FieldStatus,
	FieldApplyAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
